spring:
  application:
    name: oauth-server
#servlet的配置
  servlet:
  #文件上传相关配置项
    multipart:
      max-file-size: 16MB #单个文件大小
      max-request-size: 32MB # 设置总上传的文件大小
#spring 应用环境激活
  profiles:
    active: local
  # Jackson 配置项
  jackson:
    serialization:
      write-dates-as-timestamps: true # 设置 Date 的格式，使用时间戳
      write-date-timestamps-as-nanoseconds: false # 设置不使用 nanoseconds 的格式。例如说 1611460870.401，而是直接 1611460870401
      write-durations-as-timestamps: true # 设置 Duration 的格式，使用时间戳
      fail-on-empty-beans: false # 允许序列化无属性的 Bean
  # Cache 配置项
  cache:
    type: REDIS
    redis:
      time-to-live: 1h # 设置过期时间为 1 小时

#Mybatis plus的设置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true #显示为true
    log-impl:  org.apache.ibatis.logging.stdout.StdOutImpl # 打印日志
  global-config:
    db-config:
      id-type: auto #id设置为自增
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: ${oauth.info.base-package}.modules.*.dal.dataobject

#Spring Boot Admin 配置项
  boot:
    admin:
  # Spring Boot Admin Client 客户端的相关配置
      client:
        url: http://127.0.0.1:${server.port}/${spring.boot.admin.context-path} # 设置 Spring Boot Admin Server 地址
        instant:
          prefer-ip: true # 注册实例时，优先使用 IP
  # Spring Boot Admin Server 服务端的相关配置
      context-path: /admin # 配置 Spring

#项目相关配置项，设置当前项目所有自定义的配置
oauth:
  info:
    version: 1.0.0
    base-package: cn.iocoder.oauth
  web:
    admin-api:
      prefix: /admin-api
      controller: '**.controller.admin.**'
    app-api:
      prefix: /app-api
      controller: '**.controller.app.**'
    admin-ui:
      url: http://dashboard.oauth.iocoder.cn # Admin 管理后台 UI 的地址
  swagger:
    title: 管理后台
    description: 提供管理员管理的所有功能
    version: ${oauth.info.version}
    base-package: ${oauth.info.base-package}
  captcha:
    timeout: 5m
    width: 160
    height: 60

  sms-code: # 短信验证码相关的配置项
    id: 1663055591829
    signature: signature
    code: 123456
    api-key: LTAI5tCXLgk3rQQsMgR7FyKG
    api-secret: 6Cw9021rGsq8nzMmYnhihKD6So971O
    callbackUrl: https://aliyun.message.com
    expire-times: 10m
    send-frequency: 1m
    send-maximum-quantity-per-day: 10
    begin-code: 9999 # 这里配置 9999 的原因是，测试方便。
    end-code: 9999 # 这里配置 9999 的原因是，测试方便。