spring:
  datasource:
    #主数据源
    master:
      name: test
      jdbc-url: jdbc:mysql://127.0.0.1:3306/test?allowMultiQueries=true&useSSL=false&useUnicode=true&characterEncoding=utf-8
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
      hikari:
        maximum-pool-size: 20
        max-lifetime: 30000
        idle-timeout: 30000
        data-source-properties:
          prepStmtCacheSize: 250
          prepStmtCacheSqlLimit: 2048
          cachePrepStmts: true
          useServerPrepStmts: true
    #从数据源
    slave:
      name: test1
      jdbc-url: jdbc:mysql://127.0.0.1:3306/test1?allowMultiQueries=true&useSSL=false&useUnicode=true&characterEncoding=utf-8
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
      hikari:
        maximum-pool-size: 20
        max-lifetime: 30000
        idle-timeout: 30000
        data-source-properties:
          prepStmtCacheSize: 250
          prepStmtCacheSqlLimit: 2048
          cachePrepStmts: true
          useServerPrepStmts: true

#mybatis 配置
mybatis:
  type-aliases-package: com.spring.middleware.db.router.domain
  config-location: classpath:/mybatis-config.xml
  mapper-locations: classpath*:mybatis/*.xml