#配置数据源
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/lottery?useUnicode=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    initialSize: 10
    maxActive: 20
    maxWait: 60000

#Mybatis config
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  config-location:  classpath:/config/mybatis-config.xml

#dubbo 广播方式配置
dubbo:
  application:
    name: Lottery
    version: 1.00
  registry:
    address:  N/A #multicast://224.5.6.7:1234
  protocol:
    name: dubbo
    port: 20880
  scan:
    base-packages: com.example.lottery.rpc
